/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.cadastro.componentes.consulta;

import br.com.martinello.cadastro.view.consultas.TelaConsultaCategoriaModal;
import br.com.martinello.matriz.bd.control.CategoriaControl;
import br.com.martinello.matriz.bd.model.domain.Categoria;
import br.com.martinello.matriz.bd.util.CampoConsultaEvento;
import br.com.martinello.matriz.bd.util.CampoConsultaListener;
import br.com.martinello.matriz.componentesbasicos.Campo;
import br.com.martinello.matriz.componentesbasicos.CampoConsultaPadrao;
import br.com.martinello.matriz.componentesbasicos.CampoString;
import br.com.martinello.matriz.componentesbasicos.ConstantesGlobais;
import br.com.martinello.matriz.componentesbasicos.Rotulo;
import br.com.martinello.matriz.componentesbasicos.paineis.Painel;
import br.com.martinello.matriz.componentesbasicos.paineis.TelaProcessamento;
import com.sun.glass.events.KeyEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sidnei
 */
public class CampoConsultaCategoria extends Painel implements ActionListener, FocusListener, Campo {

    protected Categoria categoriaNew, categoriaOld, categoria;
    protected String valorOld = "", valorNew = "", valor = "";
    protected Rotulo rDescricaoProduto;
    protected CampoString csDescricaoProduto;
    protected Collection<CampoConsultaListener> campoConsultaListeners = new ArrayList<>();
    protected boolean obrigatorio = true;
    protected String origem = "T";
    protected String filtroSituacao = "N";
    protected String descricaoRotulo;
    protected Rotulo rRotulo;
    protected boolean permiteAlterarSituacao, permiteAlterarTipoEstoque;
    protected CategoriaControl categoriaControl;

    /**
     * Creates new form CampoStringConsulta
     */
    public CampoConsultaCategoria() {
        initComponents();

        //addFocusListener(this);
        ccpCategoria.getbConsultar().addActionListener(this);
        ccpCategoria.addFocusListener(this);

        SwingUtilities.invokeLater(() -> {
//            if (rotulo != null) {
//                setJlDescricao(rotulo);
//            }
//
//            if (csDescricao != null) {
//                setCsDescricao(csDescricao);
//            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clsTipoFiltro = new br.com.martinello.matriz.componentesbasicos.CampoListaSimples();
        ccpCategoria = new br.com.martinello.matriz.componentesbasicos.CampoConsultaPadrao();

        setLayout(new java.awt.BorderLayout());

        clsTipoFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Descrição", "Código" }));
        clsTipoFiltro.setSelectedIndex(1);
        clsTipoFiltro.setMaximumSize(new java.awt.Dimension(72, 20));
        clsTipoFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clsTipoFiltroItemStateChanged(evt);
            }
        });
        add(clsTipoFiltro, java.awt.BorderLayout.LINE_START);

        ccpCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ccpCategoriaKeyPressed(evt);
            }
        });
        add(ccpCategoria, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void clsTipoFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clsTipoFiltroItemStateChanged
        //cccCpfCnj.setTipo(clsTipoFiltro.getSelectedItem().toString());
    }//GEN-LAST:event_clsTipoFiltroItemStateChanged

    private void ccpCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccpCategoriaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F6) {
            abreTelaConsulta(null);
        }
    }//GEN-LAST:event_ccpCategoriaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.matriz.componentesbasicos.CampoConsultaPadrao ccpCategoria;
    private br.com.martinello.matriz.componentesbasicos.CampoListaSimples clsTipoFiltro;
    // End of variables declaration//GEN-END:variables

    public String getFiltro() {
        String filtroDescricao = "";
//        if (ValidacaoCpfCnpj.removeMascara(cccCpfCnj.getText().trim()).length() > 0) {
//            return cccCpfCnj.getText().trim();
//        }

        return filtroDescricao;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
       abreTelaConsulta(null);
    }

    public Categoria getCategoria() {
        return categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
        if (categoria != null) {
            valorOld = valorNew;

            ccpCategoria.setInt(categoria.getIdCategoria());

            valorNew = Integer.toString(categoria.getIdCategoria());

            if (rDescricaoProduto != null) {
                rDescricaoProduto.setText(categoria.getCategoria());
            }
            if (csDescricaoProduto != null) {
                csDescricaoProduto.setString(categoria.getCategoria());
                csDescricaoProduto.setEditable(false);
            }

            disparaValorSelecionado();
        } else {
            if (rDescricaoProduto != null) {
                rDescricaoProduto.setText("");
            }
            if (csDescricaoProduto != null) {
                csDescricaoProduto.setString("");
                csDescricaoProduto.setEditable(true);
            }

            disparaValorSelecionado();
        }
    }

    public CampoConsultaPadrao getCcpCategoria() {
        return ccpCategoria;
    }

    public void setCcpCategoria(CampoConsultaPadrao ccpCategoria) {
        this.ccpCategoria = ccpCategoria;
    }

    public List<Categoria> pesquisar(String campoFiltro, String filtro) {
        if (categoriaControl == null) {
            categoriaControl = new CategoriaControl();
        }
        List<Categoria> lCategoria = new LinkedList<>();

        return lCategoria;

    }

    @Override
    public void focusGained(FocusEvent e) {
        ccpCategoria.selectAll();
    }

    @Override
    public void focusLost(FocusEvent e) {
        if (ccpCategoria.getString().length() > 0 && !valorNew.equals(ccpCategoria.getString())) {

            final TelaProcessamento telaProcessamento = new TelaProcessamento("Realizando consulta...");

            new Thread() {
                @Override
                public void run() {
                     List<Categoria> lCategoria = pesquisar(clsTipoFiltro.getString(), ccpCategoria.getString());

                    if (lCategoria.size() == 1) {
                        setCategoria(lCategoria.get(0));
                    } else {
                        setCategoria(null);
                        abreTelaConsulta(lCategoria);
                    }

                    SwingUtilities.invokeLater(() -> {
                        telaProcessamento.dispose();
                    });

                }
            }.start();

            telaProcessamento.setVisible(true);
            telaProcessamento.requestFocusInWindow();

        } else if (ccpCategoria.getString().length() == 0 && !valorNew.equals("")) {
            setCategoria(null);
        }
    }

    private void abreTelaConsulta(List<Categoria> lCategoria) {
        java.awt.EventQueue.invokeLater(() -> {
            TelaConsultaCategoriaModal telaConsultaCategoria = new TelaConsultaCategoriaModal(new javax.swing.JFrame(), true, this, lCategoria);
            telaConsultaCategoria.setSize(1150, 700);
            telaConsultaCategoria.setLocationRelativeTo(null);

            if (clsTipoFiltro.getString().equals("Descrição")) {
                telaConsultaCategoria.getPainelCategoria().getCsFiltroDescricao().getClsTipoFiltro().setString("Contendo");
                telaConsultaCategoria.getPainelCategoria().getCsFiltroDescricao().getCsFiltroString().setString(ccpCategoria.getString());
            } else if (clsTipoFiltro.getString().equals("Código")) {
                telaConsultaCategoria.getPainelCategoria().getCsFiltroCodigo().setString(ccpCategoria.getString());
            }

            telaConsultaCategoria.getPainelCategoria().setPermiteAlterarSituacao(permiteAlterarSituacao);
               telaConsultaCategoria.getPainelCategoria().setOrigem(origem.toString());
            if (filtroSituacao.equalsIgnoreCase("Incluir")) {
                telaConsultaCategoria.getPainelCategoria().setaIncluir();
            } else {
                telaConsultaCategoria.getPainelCategoria().setaConsuta();
            }

            telaConsultaCategoria.getPainelCategoria().setaFocoTabelaConsulta();

            telaConsultaCategoria.setVisible(true);

        });
    }

    public Rotulo getRotuloCampo() {
        return rRotulo;
    }

    @Override
    public Rotulo getComponenteRotulo() {
        return rRotulo;
    }

    @Override
    public void setComponenteRotulo(Rotulo rRotulo) {
        this.rRotulo = rRotulo;

        atualizaDescricaoRotulo();
    }

    public Rotulo getrDescricaoProduto() {
        return rDescricaoProduto;
    }

    public void setrDescricaoProduto(Rotulo rDescricaoProduto) {
        this.rDescricaoProduto = rDescricaoProduto;
    }

    public CampoString getCsDescricaoProduto() {
        return csDescricaoProduto;
    }

    public void setCsDescricaoProduto(CampoString csDescricaoProduto) {
        this.csDescricaoProduto = csDescricaoProduto;
    }

    public synchronized void addCampoConsultaListener(CampoConsultaListener l) {
        if (!campoConsultaListeners.contains(l)) {
            campoConsultaListeners.add(l);
        }
    }

    public synchronized void removeCampoConsultaListener(CampoConsultaListener l) {
        campoConsultaListeners.remove(l);
    }

    private void disparaValorSelecionado() {
        Collection<CampoConsultaListener> tl;

        synchronized (this) {
            tl = (Collection) (((ArrayList) campoConsultaListeners).clone());
        }

        CampoConsultaEvento evento = new CampoConsultaEvento(this);

        tl.forEach((t) -> {
            t.valorSelecionado(evento);
        });
    }

    @Override
    public void limpar() {
        this.valorOld = valorNew;
        this.valorNew = "";
        setCategoria(null);
        clsTipoFiltro.setSelectedIndex(0);
        ccpCategoria.setString("");
       
        ccpCategoria.limpar();
    }

    @Override
    public boolean eValido() {
        return true;
    }

    @Override
    public boolean eVazio() {
        if (obrigatorio) {
            if (categoria != null) {
                ccpCategoria.setBorder(ccpCategoria.getBordaOriginal());
                return false;
            } else {
                ccpCategoria.setBorder(ConstantesGlobais.BORDA_ERRO);
                return true;
            }
        }
        return false;
    }

    @Override
    public String getDica() {
        return "";
    }

    @Override
    public String getDescricaoRotulo() {
        return descricaoRotulo;
    }

    @Override
    public void setDescricaoRotulo(String descricaoRotulo) {
        this.descricaoRotulo = descricaoRotulo;
    }

    @Override
    public boolean isObrigatorio() {
        return obrigatorio;
    }

    @Override
    public void setObrigatorio(boolean obrigatorio) {
        this.obrigatorio = obrigatorio;
    }

    public void atualizaDescricaoRotulo() {
        if (rRotulo != null) {
            SwingUtilities.invokeLater(() -> {
                if (obrigatorio) {
                    rRotulo.setText("<html><body>" + descricaoRotulo + "<FONT COLOR='red'><b>*</b></FONT>:</body></html>");
                } else {
                    rRotulo.setText("<html><body>" + descricaoRotulo + ":</body></html>");
                }
            });
        }
    }

    public String getOrigem() {
        return origem;
    }

    public void setOrigem(String origem) {
        this.origem = origem;
    }

    public boolean isPermiteAlterarSituacao() {
        return permiteAlterarSituacao;
    }

    public void setPermiteAlterarSituacao(boolean permiteAlterarSituacao) {
        this.permiteAlterarSituacao = permiteAlterarSituacao;
    }

    public boolean isPermiteAlterarTipoEstoque() {
        return permiteAlterarTipoEstoque;
    }

    public void setPermiteAlterarTipoEstoque(boolean permiteAlterarTipoEstoque) {
        this.permiteAlterarTipoEstoque = permiteAlterarTipoEstoque;
    }

    public String getFiltroSituacao() {
        return filtroSituacao;
    }

    public void setFiltroSituacao(String filtroSituacao) {
        this.filtroSituacao = filtroSituacao;
    }

    @Override
    public void setEnabled(boolean habilitado) {
        clsTipoFiltro.setEnabled(habilitado);
        ccpCategoria.setEnabled(habilitado);
    }

    @Override

    public void grabFocus() {
        ccpCategoria.grabFocus();
    }
}
