/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.gerenciador.view;

import br.com.martinello.componentesbasicos.Campo;
import br.com.martinello.componentesbasicos.ConstantesGlobais;
import br.com.martinello.gerenciador.componentes.ConsultavelLoja;
import br.com.martinello.gerenciador.componentes.ConsultavelPerfil;
import br.com.martinello.bd.matriz.control.UsuarioControl;
import br.com.martinello.bd.matriz.integracao.model.domain.Loja;
import br.com.martinello.bd.matriz.model.domain.Menu;
import br.com.martinello.bd.matriz.model.domain.Perfil;
import br.com.martinello.bd.matriz.model.domain.Usuario;
import br.com.martinello.componentesbasicos.paineis.JPStatus;
import br.com.martinello.util.excessoes.ErroSistemaException;
import br.com.martinello.util.filtro.Filtro;
import com.towel.swing.table.ObjectTableModel;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sidnei
 */
public class TelaUsuarios extends TelaPadrao {

    protected ObjectTableModel<Usuario> otmConsultaUsuarios = new ObjectTableModel(Usuario.class, "loja,codigoAnterior,nome,login,validade,fechaCaixa,liberaVenda,consultaPreco,nivelLiberacao,dataHoraCadastro,dataHoraAtualizacao");

    protected UsuarioControl usuarioControl;

    private List<Campo> listaCampoUsuario = new ArrayList<>();

    protected ObjectTableModel<Menu> otmConsultaUsuarioMenus = new ObjectTableModel(Menu.class, "menuPai,menu,descricao");
    protected ObjectTableModel<Menu> otmCadastroUsuarioMenus = new ObjectTableModel(Menu.class, "menuPai,menu,descricao");
    protected ObjectTableModel<Menu> otmCadastroMenusDisponiveis = new ObjectTableModel(Menu.class, "menuPai,menu,descricao");

    public TelaUsuarios() {
        initComponents();

        try {
            usuarioControl = new UsuarioControl();
        } catch (ErroSistemaException ex) {
            jpsStatusBar.setStatus(ex.getLocalizedMessage(), JPStatus.ERRO, ex);
        }

        carregarCampos();

        jtpUsuarios.setEnabledAt(1, false);

        ccLoja.setJlDescricao(jlNomeLoja);

        otmConsultaUsuarios.setData(usuarioControl.getlConsultaUsuarios());
        tpConsultaUsuarios.packAll();

        tpConsultaUsuarios.getSelectionModel().addListSelectionListener((ListSelectionEvent evt) -> {
            if (evt.getValueIsAdjusting()) {
                return;
            }

            if (tpConsultaUsuarios.getSelectedRow() >= 0) {
                Usuario usuarioSelecionado = otmConsultaUsuarios.getValue(tpConsultaUsuarios.convertRowIndexToModel(tpConsultaUsuarios.getSelectedRow()));
                usuarioControl.setUsuario(usuarioSelecionado);

                otmConsultaUsuarioMenus.setData(usuarioSelecionado.getlUsuariosMenus());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpUsuarios = new br.com.martinello.componentesbasicos.paineis.PainelAba();
        jpConsulta = new br.com.martinello.componentesbasicos.paineis.Painel();
        jpFiltros = new br.com.martinello.componentesbasicos.paineis.Painel();
        jlFiltroLoja = new br.com.martinello.componentesbasicos.Rotulo();
        jlFiltroNome = new br.com.martinello.componentesbasicos.Rotulo();
        csFiltroLoja = new br.com.martinello.componentesbasicos.CampoString();
        bPequisar = new br.com.martinello.componentesbasicos.Botao();
        bExcluir = new br.com.martinello.componentesbasicos.Botao();
        bAlterar = new br.com.martinello.componentesbasicos.Botao();
        bIncluir = new br.com.martinello.componentesbasicos.Botao();
        cscFiltroNome = new br.com.martinello.componentesbasicos.consulta.CampoStringConsulta();
        bImportarDBF = new br.com.martinello.componentesbasicos.Botao();
        jspUsuarios = new javax.swing.JScrollPane();
        tpConsultaUsuarios = new br.com.martinello.componentesbasicos.TabelaPadrao();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpConsultaUsuarioMenus = new br.com.martinello.componentesbasicos.TabelaPadrao();
        jpCadastro = new br.com.martinello.componentesbasicos.paineis.Painel();
        paCadastroUsuario = new br.com.martinello.componentesbasicos.paineis.PainelAba();
        pDadosUsuarios = new br.com.martinello.componentesbasicos.paineis.Painel();
        clNivelLiberacao = new br.com.martinello.componentesbasicos.CampoListaSimples(Usuario.class,"nivelLiberacao");
        jlNomeLoja = new br.com.martinello.componentesbasicos.Rotulo();
        rConsultaPreco = new br.com.martinello.componentesbasicos.Rotulo();
        csSenha = new br.com.martinello.componentesbasicos.CampoSenha(Usuario.class,"senha");
        rLogin = new br.com.martinello.componentesbasicos.Rotulo();
        rNivelLiberacao = new br.com.martinello.componentesbasicos.Rotulo();
        rCodigo = new br.com.martinello.componentesbasicos.Rotulo();
        csDataHoraCadastro = new br.com.martinello.componentesbasicos.CampoString(Usuario.class,"dataHoraCadastro");
        clConsultaPreco = new br.com.martinello.gerenciador.componentes.CampoLista(Usuario.class,"consultaPreco","SimNao");
        clLiberaVenda = new br.com.martinello.gerenciador.componentes.CampoLista(Usuario.class,"liberaVenda","SimNao");
        clFechaCaixa = new br.com.martinello.gerenciador.componentes.CampoLista(Usuario.class,"fechaCaixa","SimNao");
        rStatus = new br.com.martinello.componentesbasicos.Rotulo();
        rLoja = new br.com.martinello.componentesbasicos.Rotulo();
        rSenha = new br.com.martinello.componentesbasicos.Rotulo();
        rDataHoraCadastro = new br.com.martinello.componentesbasicos.Rotulo();
        rLiberaVenda = new br.com.martinello.componentesbasicos.Rotulo();
        rNome = new br.com.martinello.componentesbasicos.Rotulo();
        csDataHoraAtualizacao = new br.com.martinello.componentesbasicos.CampoString(Usuario.class,"dataHoraAtualizacao");
        csLogin = new br.com.martinello.componentesbasicos.CampoString(Usuario.class,"login");
        csNome = new br.com.martinello.componentesbasicos.CampoString(Usuario.class,"nome");
        csCodigoAnterior = new br.com.martinello.componentesbasicos.CampoString(Usuario.class,"codigoAnterior");
        ccLoja = new br.com.martinello.gerenciador.componentes.CampoConsulta(new ConsultavelLoja(Loja.class, "codigo"), Usuario.class, "loja","Loja", jlNomeLoja, "");
        rDataHoraAtualizacao = new br.com.martinello.componentesbasicos.Rotulo();
        rFechaCaixa = new br.com.martinello.componentesbasicos.Rotulo();
        cdValidade = new br.com.martinello.componentesbasicos.CampoData(Usuario.class,"validade");
        rDesbloqueiaCliente = new br.com.martinello.componentesbasicos.Rotulo();
        clDesbloqueiaCliente = new br.com.martinello.gerenciador.componentes.CampoLista(Usuario.class,"fechaCaixa","SimNao");
        rReabilitaVenda = new br.com.martinello.componentesbasicos.Rotulo();
        clReabilitaVenda = new br.com.martinello.gerenciador.componentes.CampoLista(Usuario.class,"liberaVenda","SimNao");
        rClassificacao = new br.com.martinello.componentesbasicos.Rotulo();
        clClassificacao = new br.com.martinello.gerenciador.componentes.CampoLista(Usuario.class,"classificacao","ClassificacaoUsuario");
        pMenusUsuarios = new br.com.martinello.componentesbasicos.paineis.Painel();
        jPanel3 = new br.com.martinello.componentesbasicos.paineis.Painel();
        jLabel1 = new br.com.martinello.componentesbasicos.Rotulo();
        jLabel2 = new br.com.martinello.componentesbasicos.Rotulo();
        jbRemoverMenu = new br.com.martinello.componentesbasicos.Botao();
        jbAdicionarMenu = new br.com.martinello.componentesbasicos.Botao();
        jspCadastroMenusDisponiveis = new javax.swing.JScrollPane();
        tpCadastroMenusDisponiveis = new br.com.martinello.componentesbasicos.TabelaPadrao();
        jspCadastroMenusPerfil = new javax.swing.JScrollPane();
        tpCadastroMenusPerfil = new br.com.martinello.componentesbasicos.TabelaPadrao();
        jPanel4 = new br.com.martinello.componentesbasicos.paineis.Painel();
        ccPerfilAtribuir = new br.com.martinello.gerenciador.componentes.CampoConsulta(new ConsultavelPerfil(Perfil.class, "idPerfil"), Perfil.class, "idPerfil","Perfil", null, "");
        jButton1 = new br.com.martinello.componentesbasicos.Botao();
        pBotoes = new br.com.martinello.componentesbasicos.paineis.Painel();
        jbSalvar = new br.com.martinello.componentesbasicos.Botao();
        jbCancelar = new br.com.martinello.componentesbasicos.Botao();
        jpsStatusBar = new br.com.martinello.componentesbasicos.paineis.JPStatus();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerênciamento de Usuários");

        jpFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ConstantesGlobais.FONTE_11_NORMAL));

        jlFiltroLoja.setText("Loja:");

        jlFiltroNome.setText("Nome:");

        bPequisar.setMnemonic('p');
        bPequisar.setText("Pesquisar");
        bPequisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPequisarActionPerformed(evt);
            }
        });

        bExcluir.setMnemonic('e');
        bExcluir.setText("Excluir");

        bAlterar.setMnemonic('a');
        bAlterar.setText("Alterar");
        bAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarActionPerformed(evt);
            }
        });

        bIncluir.setMnemonic('i');
        bIncluir.setText("Incluir");
        bIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIncluirActionPerformed(evt);
            }
        });

        bImportarDBF.setMnemonic('p');
        bImportarDBF.setText("Imp. DBF");
        bImportarDBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImportarDBFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFiltrosLayout = new javax.swing.GroupLayout(jpFiltros);
        jpFiltros.setLayout(jpFiltrosLayout);
        jpFiltrosLayout.setHorizontalGroup(
            jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiltrosLayout.createSequentialGroup()
                .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFiltrosLayout.createSequentialGroup()
                        .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlFiltroNome, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jlFiltroLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFiltrosLayout.createSequentialGroup()
                                .addComponent(csFiltroLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cscFiltroNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFiltrosLayout.createSequentialGroup()
                        .addGap(0, 526, Short.MAX_VALUE)
                        .addComponent(bPequisar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bImportarDBF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jpFiltrosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlFiltroLoja, jlFiltroNome});

        jpFiltrosLayout.setVerticalGroup(
            jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiltrosLayout.createSequentialGroup()
                .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlFiltroLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csFiltroLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cscFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bPequisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bImportarDBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpFiltrosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {csFiltroLoja, cscFiltroNome, jlFiltroLoja, jlFiltroNome});

        tpConsultaUsuarios.setModel(otmConsultaUsuarios);
        tpConsultaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpConsultaUsuariosMouseClicked(evt);
            }
        });
        jspUsuarios.setViewportView(tpConsultaUsuarios);

        tpConsultaUsuarioMenus.setModel(otmConsultaUsuarioMenus);
        jScrollPane1.setViewportView(tpConsultaUsuarioMenus);

        javax.swing.GroupLayout jpConsultaLayout = new javax.swing.GroupLayout(jpConsulta);
        jpConsulta.setLayout(jpConsultaLayout);
        jpConsultaLayout.setHorizontalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jspUsuarios, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1)
        );
        jpConsultaLayout.setVerticalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addComponent(jpFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpUsuarios.addTab("Consulta", jpConsulta);

        jpCadastro.setLayout(new java.awt.BorderLayout());

        pDadosUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clNivelLiberacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3" }));
        clNivelLiberacao.setComponenteRotulo(rNivelLiberacao);
        clNivelLiberacao.setDescricaoRotulo("Nível Liberação");
        clNivelLiberacao.setObrigatorio(true);

        jlNomeLoja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlNomeLoja.setText(" ");

        csSenha.setComponenteRotulo(rSenha);
        csSenha.setDescricaoRotulo("Senha");
        csSenha.setObrigatorio(true);

        csDataHoraCadastro.setEditable(false);
        csDataHoraCadastro.setComponenteRotulo(rDataHoraCadastro);
        csDataHoraCadastro.setDescricaoRotulo("Data/Hora Cad.");

        clConsultaPreco.setComponenteRotulo(rConsultaPreco);
        clConsultaPreco.setDescricaoRotulo("Consulta Preço");
        clConsultaPreco.setObrigatorio(true);

        clLiberaVenda.setComponenteRotulo(rLiberaVenda);
        clLiberaVenda.setDescricaoRotulo("Libera Venda");
        clLiberaVenda.setObrigatorio(true);

        clFechaCaixa.setComponenteRotulo(rFechaCaixa);
        clFechaCaixa.setDescricaoRotulo("Fecha Caixa");
        clFechaCaixa.setObrigatorio(true);

        csDataHoraAtualizacao.setEditable(false);
        csDataHoraAtualizacao.setComponenteRotulo(rDataHoraAtualizacao);
        csDataHoraAtualizacao.setDescricaoRotulo("Data/Hora Atu.");

        csLogin.setComponenteRotulo(rLogin);
        csLogin.setDescricaoRotulo("Login");
        csLogin.setObrigatorio(true);

        csNome.setComponenteRotulo(rNome);
        csNome.setDescricaoRotulo("Nome");
        csNome.setObrigatorio(true);

        csCodigoAnterior.setComponenteRotulo(rCodigo);
        csCodigoAnterior.setDescricaoRotulo("Código");

        ccLoja.setComponenteRotulo(rLoja);
        ccLoja.setDescricaoRotulo("Loja");
        ccLoja.setObrigatorio(true);

        cdValidade.setComponenteRotulo(rStatus);
        cdValidade.setDescricaoRotulo("Status");

        clDesbloqueiaCliente.setComponenteRotulo(rDesbloqueiaCliente);
        clDesbloqueiaCliente.setDescricaoRotulo("Desbl. CLiente");
        clDesbloqueiaCliente.setObrigatorio(true);

        clReabilitaVenda.setComponenteRotulo(rReabilitaVenda);
        clReabilitaVenda.setDescricaoRotulo("Reabilita Venda");
        clReabilitaVenda.setObrigatorio(true);

        clClassificacao.setComponenteRotulo(rClassificacao);
        clClassificacao.setDescricaoRotulo("Classificação");
        clClassificacao.setObrigatorio(true);

        javax.swing.GroupLayout pDadosUsuariosLayout = new javax.swing.GroupLayout(pDadosUsuarios);
        pDadosUsuarios.setLayout(pDadosUsuariosLayout);
        pDadosUsuariosLayout.setHorizontalGroup(
            pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                        .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosUsuariosLayout.createSequentialGroup()
                                        .addComponent(rLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ccLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosUsuariosLayout.createSequentialGroup()
                                        .addComponent(rCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(csCodigoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                                .addComponent(rLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(csLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                                .addComponent(rDesbloqueiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clDesbloqueiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rDataHoraCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rDataHoraAtualizacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(csDataHoraCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csDataHoraAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                                .addComponent(rStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                                    .addComponent(rReabilitaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(clReabilitaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosUsuariosLayout.createSequentialGroup()
                                        .addComponent(rNivelLiberacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clNivelLiberacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosUsuariosLayout.createSequentialGroup()
                                        .addComponent(rConsultaPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clConsultaPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosUsuariosLayout.createSequentialGroup()
                                        .addComponent(rLiberaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clLiberaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosUsuariosLayout.createSequentialGroup()
                                        .addComponent(rFechaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clFechaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE))
                    .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosUsuariosLayout.createSequentialGroup()
                            .addComponent(rSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(csSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(357, 357, 357))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosUsuariosLayout.createSequentialGroup()
                            .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(88, 88, 88))
            .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                .addComponent(rClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDadosUsuariosLayout.setVerticalGroup(
            pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCodigoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rFechaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clFechaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clLiberaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rLiberaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clReabilitaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rReabilitaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rConsultaPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clConsultaPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clNivelLiberacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rNivelLiberacao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDesbloqueiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clDesbloqueiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataHoraCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csDataHoraCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataHoraAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csDataHoraAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        paCadastroUsuario.addTab("Dados Usuário", pDadosUsuarios);

        pMenusUsuarios.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ConstantesGlobais.FONTE_11_NORMAL));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Selecionados");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Disponíveis");

        jbRemoverMenu.setText("<");
        jbRemoverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverMenuActionPerformed(evt);
            }
        });

        jbAdicionarMenu.setText(">");
        jbAdicionarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarMenuActionPerformed(evt);
            }
        });

        tpCadastroMenusDisponiveis.setModel(otmCadastroMenusDisponiveis);
        tpCadastroMenusDisponiveis.setShowGrid(true);
        jspCadastroMenusDisponiveis.setViewportView(tpCadastroMenusDisponiveis);

        tpCadastroMenusPerfil.setModel(otmCadastroUsuarioMenus);
        jspCadastroMenusPerfil.setViewportView(tpCadastroMenusPerfil);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jspCadastroMenusDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbAdicionarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbRemoverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspCadastroMenusPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jbAdicionarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRemoverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jspCadastroMenusDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspCadastroMenusPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pMenusUsuarios.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ConstantesGlobais.FONTE_11_NORMAL));

        jButton1.setText("Atribuir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccPerfilAtribuir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccPerfilAtribuir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pMenusUsuarios.add(jPanel4, java.awt.BorderLayout.NORTH);

        paCadastroUsuario.addTab("Menus Usuário", pMenusUsuarios);

        jpCadastro.add(paCadastroUsuario, java.awt.BorderLayout.CENTER);

        pBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbSalvar.setMnemonic('s');
        jbSalvar.setText("Salvar");
        jbSalvar.setPreferredSize(new java.awt.Dimension(85, 23));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        pBotoes.add(jbSalvar);

        jbCancelar.setMnemonic('c');
        jbCancelar.setText("Cancelar");
        jbCancelar.setPreferredSize(new java.awt.Dimension(85, 23));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        pBotoes.add(jbCancelar);

        jpCadastro.add(pBotoes, java.awt.BorderLayout.SOUTH);

        jtpUsuarios.addTab("Cadastro/Alteração", jpCadastro);

        getContentPane().add(jtpUsuarios, java.awt.BorderLayout.CENTER);
        getContentPane().add(jpsStatusBar, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIncluirActionPerformed
        usuarioControl.novo();
        limparListaCampos(listaCampoUsuario);

        otmCadastroUsuarioMenus.setData(usuarioControl.getUsuario().getlUsuariosMenus());
        otmCadastroMenusDisponiveis.setData(usuarioControl.getlMenusDisponiveis());

        statusTela = INCLUINDO;
        habilitaComponentesCadastro(true);
        habilitaCadastro(true);
        habilitaBotoesColunas(true);
    }//GEN-LAST:event_bIncluirActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        habilitaCadastro(false);
        statusTela = INDEFINIDO;
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            if (statusTela == INCLUINDO || statusTela == ALTERANDO) {
                if (!validarListaCampos(listaCampoUsuario)) {
                    jpsStatusBar.setStatus("Campos obrigatórios não preenchidos.", JPStatus.ALERTA);
                    return;
                }

                setDadosUsuario();

                usuarioControl.salvar();

            } else {
                usuarioControl.excluir();
            }

            otmConsultaUsuarios.fireTableDataChanged();
            otmConsultaUsuarioMenus.fireTableDataChanged();
            tpConsultaUsuarios.packAll();

            if (statusTela == INCLUINDO || statusTela == ALTERANDO) {
                int posicaoLinha = usuarioControl.getlConsultaUsuarios().indexOf(usuarioControl.getUsuario());
                tpConsultaUsuarios.addRowSelectionInterval(tpConsultaUsuarios.convertRowIndexToView(posicaoLinha), tpConsultaUsuarios.convertRowIndexToView(posicaoLinha));
                tpConsultaUsuarios.scrollRectToVisible(tpConsultaUsuarios.getCellRect(tpConsultaUsuarios.getSelectedRow(), 0, true));
            }

            jpsStatusBar.setStatus("Processamento efetuado com sucesso.", JPStatus.NORMAL);
            habilitaCadastro(false);
            statusTela = INDEFINIDO;

        } catch (ErroSistemaException ex) {
            jpsStatusBar.setStatus(ex.getLocalizedMessage(), JPStatus.ALERTA);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void bAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarActionPerformed
        alterarUsuario();
    }//GEN-LAST:event_bAlterarActionPerformed

    private void bPequisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPequisarActionPerformed
        List<Filtro> lFiltros = new LinkedList<>();
        if (csFiltroLoja.getString().length() > 0) {
            Loja loja = new Loja();
            loja.setCodigo(csFiltroLoja.getString());
            lFiltros.add(new Filtro("codigo", Filtro.LOJA, Filtro.IGUAL, loja));
        }
        lFiltros.add(cscFiltroNome.getFiltro("nome"));

        try {
            usuarioControl.pesquisarNovo(lFiltros);

            otmConsultaUsuarios.fireTableDataChanged();

            tpConsultaUsuarios.packAll();
        } catch (ErroSistemaException ex) {
            jpsStatusBar.setStatus("Erro ao realizar a consulta", JPStatus.ERRO, ex);
        }
    }//GEN-LAST:event_bPequisarActionPerformed

    private void tpConsultaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpConsultaUsuariosMouseClicked
        if (evt.getClickCount() == 2) {
            alterarUsuario();
        }
    }//GEN-LAST:event_tpConsultaUsuariosMouseClicked

    private void jbRemoverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverMenuActionPerformed
        if (tpCadastroMenusPerfil.getSelectedRow() >= 0) {
            usuarioControl.removerMenus(otmCadastroUsuarioMenus.getList(tpCadastroMenusPerfil.getLinhasSelecionadas()));

            otmCadastroUsuarioMenus.fireTableDataChanged();
            otmCadastroMenusDisponiveis.fireTableDataChanged();
        }
    }//GEN-LAST:event_jbRemoverMenuActionPerformed

    private void jbAdicionarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarMenuActionPerformed
        if (tpCadastroMenusDisponiveis.getSelectedRow() >= 0) {
            usuarioControl.adicionarMenus(otmCadastroMenusDisponiveis.getList(tpCadastroMenusDisponiveis.getLinhasSelecionadas()));

            otmCadastroUsuarioMenus.fireTableDataChanged();
            otmCadastroMenusDisponiveis.fireTableDataChanged();
        }
    }//GEN-LAST:event_jbAdicionarMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Perfil perfilAtribuir = (Perfil) ccPerfilAtribuir.getValor();

        if (perfilAtribuir != null) {
            usuarioControl.atribuirPerfil(perfilAtribuir);

            otmCadastroMenusDisponiveis.fireTableDataChanged();
            otmCadastroUsuarioMenus.fireTableDataChanged();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bImportarDBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImportarDBFActionPerformed
        JFileChooser jfcLocalizarArquivo = new JFileChooser();
        jfcLocalizarArquivo.setFileFilter(new FileNameExtensionFilter("DBF (*.dbf)", "dbf"));
        jfcLocalizarArquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfcLocalizarArquivo.setDialogTitle("Importar Usuários SGL");
        int result = jfcLocalizarArquivo.showOpenDialog(jfcLocalizarArquivo);
        if (result == JFileChooser.APPROVE_OPTION) {
            String local = jfcLocalizarArquivo.getSelectedFile().getAbsolutePath();
            try {
                File arquivoUsuarios = new File(local);
                usuarioControl.importarUsuariosSGL(arquivoUsuarios);
            } catch (ErroSistemaException ex) {
                jpsStatusBar.setStatus(ex.getLocalizedMessage(), JPStatus.ERRO, ex);
            }
        }

    }//GEN-LAST:event_bImportarDBFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Botao bAlterar;
    private br.com.martinello.componentesbasicos.Botao bExcluir;
    private br.com.martinello.componentesbasicos.Botao bImportarDBF;
    private br.com.martinello.componentesbasicos.Botao bIncluir;
    private br.com.martinello.componentesbasicos.Botao bPequisar;
    private br.com.martinello.gerenciador.componentes.CampoConsulta ccLoja;
    private br.com.martinello.gerenciador.componentes.CampoConsulta ccPerfilAtribuir;
    private br.com.martinello.componentesbasicos.CampoData cdValidade;
    private br.com.martinello.gerenciador.componentes.CampoLista clClassificacao;
    private br.com.martinello.gerenciador.componentes.CampoLista clConsultaPreco;
    private br.com.martinello.gerenciador.componentes.CampoLista clDesbloqueiaCliente;
    private br.com.martinello.gerenciador.componentes.CampoLista clFechaCaixa;
    private br.com.martinello.gerenciador.componentes.CampoLista clLiberaVenda;
    private br.com.martinello.componentesbasicos.CampoListaSimples clNivelLiberacao;
    private br.com.martinello.gerenciador.componentes.CampoLista clReabilitaVenda;
    private br.com.martinello.componentesbasicos.CampoString csCodigoAnterior;
    private br.com.martinello.componentesbasicos.CampoString csDataHoraAtualizacao;
    private br.com.martinello.componentesbasicos.CampoString csDataHoraCadastro;
    private br.com.martinello.componentesbasicos.CampoString csFiltroLoja;
    private br.com.martinello.componentesbasicos.CampoString csLogin;
    private br.com.martinello.componentesbasicos.CampoString csNome;
    private br.com.martinello.componentesbasicos.CampoSenha csSenha;
    private br.com.martinello.componentesbasicos.consulta.CampoStringConsulta cscFiltroNome;
    private br.com.martinello.componentesbasicos.Botao jButton1;
    private br.com.martinello.componentesbasicos.Rotulo jLabel1;
    private br.com.martinello.componentesbasicos.Rotulo jLabel2;
    private br.com.martinello.componentesbasicos.paineis.Painel jPanel3;
    private br.com.martinello.componentesbasicos.paineis.Painel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private br.com.martinello.componentesbasicos.Botao jbAdicionarMenu;
    private br.com.martinello.componentesbasicos.Botao jbCancelar;
    private br.com.martinello.componentesbasicos.Botao jbRemoverMenu;
    private br.com.martinello.componentesbasicos.Botao jbSalvar;
    private br.com.martinello.componentesbasicos.Rotulo jlFiltroLoja;
    private br.com.martinello.componentesbasicos.Rotulo jlFiltroNome;
    private br.com.martinello.componentesbasicos.Rotulo jlNomeLoja;
    private br.com.martinello.componentesbasicos.paineis.Painel jpCadastro;
    private br.com.martinello.componentesbasicos.paineis.Painel jpConsulta;
    private br.com.martinello.componentesbasicos.paineis.Painel jpFiltros;
    private br.com.martinello.componentesbasicos.paineis.JPStatus jpsStatusBar;
    private javax.swing.JScrollPane jspCadastroMenusDisponiveis;
    private javax.swing.JScrollPane jspCadastroMenusPerfil;
    private javax.swing.JScrollPane jspUsuarios;
    private br.com.martinello.componentesbasicos.paineis.PainelAba jtpUsuarios;
    private br.com.martinello.componentesbasicos.paineis.Painel pBotoes;
    private br.com.martinello.componentesbasicos.paineis.Painel pDadosUsuarios;
    private br.com.martinello.componentesbasicos.paineis.Painel pMenusUsuarios;
    private br.com.martinello.componentesbasicos.paineis.PainelAba paCadastroUsuario;
    private br.com.martinello.componentesbasicos.Rotulo rClassificacao;
    private br.com.martinello.componentesbasicos.Rotulo rCodigo;
    private br.com.martinello.componentesbasicos.Rotulo rConsultaPreco;
    private br.com.martinello.componentesbasicos.Rotulo rDataHoraAtualizacao;
    private br.com.martinello.componentesbasicos.Rotulo rDataHoraCadastro;
    private br.com.martinello.componentesbasicos.Rotulo rDesbloqueiaCliente;
    private br.com.martinello.componentesbasicos.Rotulo rFechaCaixa;
    private br.com.martinello.componentesbasicos.Rotulo rLiberaVenda;
    private br.com.martinello.componentesbasicos.Rotulo rLogin;
    private br.com.martinello.componentesbasicos.Rotulo rLoja;
    private br.com.martinello.componentesbasicos.Rotulo rNivelLiberacao;
    private br.com.martinello.componentesbasicos.Rotulo rNome;
    private br.com.martinello.componentesbasicos.Rotulo rReabilitaVenda;
    private br.com.martinello.componentesbasicos.Rotulo rSenha;
    private br.com.martinello.componentesbasicos.Rotulo rStatus;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpCadastroMenusDisponiveis;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpCadastroMenusPerfil;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpConsultaUsuarioMenus;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpConsultaUsuarios;
    // End of variables declaration//GEN-END:variables

    private void alterarUsuario() {
        if (tpConsultaUsuarios.getSelectedRow() >= 0) {
            getDadosUsuario();

            otmCadastroUsuarioMenus.setData(usuarioControl.getUsuario().getlUsuariosMenus());
            otmCadastroMenusDisponiveis.setData(usuarioControl.getlMenusDisponiveis());
            otmCadastroUsuarioMenus.fireTableDataChanged();
            otmCadastroMenusDisponiveis.fireTableDataChanged();

            habilitaComponentesCadastro(true);
            habilitaCadastro(true);
            habilitaBotoesColunas(true);

            statusTela = ALTERANDO;
        } else {
            jpsStatusBar.setStatus("É necessário selecionar um usuário.", JPStatus.ALERTA);
        }
    }

    public void carregarCampos() {
        listaCampoUsuario.add(ccLoja);
        listaCampoUsuario.add(csCodigoAnterior);
        listaCampoUsuario.add(csNome);
        listaCampoUsuario.add(csLogin);
        listaCampoUsuario.add(csSenha);
        listaCampoUsuario.add(clClassificacao);
        listaCampoUsuario.add(clFechaCaixa);
        listaCampoUsuario.add(clLiberaVenda);
        listaCampoUsuario.add(clReabilitaVenda);
        listaCampoUsuario.add(clConsultaPreco);
        listaCampoUsuario.add(clNivelLiberacao);
        listaCampoUsuario.add(clDesbloqueiaCliente);
        listaCampoUsuario.add(cdValidade);
    }

    @Override
    public void habilitaComponentesCadastro(boolean habilita) {
        habilitaPainel(habilita, jpCadastro);
    }

    @Override
    public void habilitaCadastro(boolean habilitada) {
        jtpUsuarios.setEnabledAt(0, !habilitada);
        jtpUsuarios.setEnabledAt(1, habilitada);
        jtpUsuarios.setSelectedIndex(habilitada ? 1 : 0);
    }

    private void setDadosUsuario() {
        usuarioControl.getUsuario().setLoja((Loja) ccLoja.getValor());
        usuarioControl.getUsuario().setCodigoAnterior(csCodigoAnterior.getString());
        usuarioControl.getUsuario().setNome(csNome.getString());
        usuarioControl.getUsuario().setLogin(csLogin.getString());
        usuarioControl.getUsuario().setSenha(csSenha.getString());
        usuarioControl.getUsuario().setClassificacao(clClassificacao.getString());
        usuarioControl.getUsuario().setFechaCaixa(clFechaCaixa.getString());
        usuarioControl.getUsuario().setLiberaVenda(clLiberaVenda.getString());
        usuarioControl.getUsuario().setReabilitaVenda(clReabilitaVenda.getString());
        usuarioControl.getUsuario().setConsultaPreco(clConsultaPreco.getString());
        usuarioControl.getUsuario().setNivelLiberacao(clNivelLiberacao.getInt());
        usuarioControl.getUsuario().setDesbloqueiaCliente(clDesbloqueiaCliente.getString());
        usuarioControl.getUsuario().setValidade(cdValidade.getDate());
    }

    private void getDadosUsuario() {
        ccLoja.setValor(usuarioControl.getUsuario().getLoja());
        csCodigoAnterior.setString(usuarioControl.getUsuario().getCodigoAnterior());
        csNome.setString(usuarioControl.getUsuario().getNome());
        csLogin.setString(usuarioControl.getUsuario().getLogin());
        csSenha.setString(usuarioControl.getUsuario().getSenha());
        clClassificacao.setString(usuarioControl.getUsuario().getClassificacao());
        clFechaCaixa.setString(usuarioControl.getUsuario().getFechaCaixa());
        clLiberaVenda.setString(usuarioControl.getUsuario().getLiberaVenda());
        clReabilitaVenda.setString(usuarioControl.getUsuario().getReabilitaVenda());
        clConsultaPreco.setString(usuarioControl.getUsuario().getConsultaPreco());
        clNivelLiberacao.setInt(usuarioControl.getUsuario().getNivelLiberacao());
        clDesbloqueiaCliente.setString(usuarioControl.getUsuario().getDesbloqueiaCliente());
        cdValidade.setDate(usuarioControl.getUsuario().getValidade());
        csDataHoraCadastro.setDate(usuarioControl.getUsuario().getDataHoraCadastro(), "dd/MM/yyyy hh:mm:ss");
        csDataHoraAtualizacao.setDate(usuarioControl.getUsuario().getDataHoraAtualizacao(), "dd/MM/yyyy hh:mm:ss");
    }

}
