/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.gerenciador.view;

import br.com.martinello.bd.matriz.control.VersaoControl;
import br.com.martinello.bd.matriz.model.domain.Versao;
import br.com.martinello.componentesbasicos.Campo;
import br.com.martinello.componentesbasicos.ConstantesGlobais;
import br.com.martinello.componentesbasicos.paineis.JPStatus;
import br.com.martinello.util.excessoes.ErroSistemaException;
import br.com.martinello.util.filtro.Filtro;
import com.towel.swing.table.ObjectTableModel;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author sidnei.vieira
 */
public class TelaVersao extends TelaPadrao {

    private VersaoControl versaoControl;

    protected ObjectTableModel<Versao> otmConsultaVersao = new ObjectTableModel(Versao.class, "sistema,descricao,versaoPrincipal,versaoSecundaria,versaoPath");

    private List<Campo> listaCampoVersao = new ArrayList<>();

    /**
     * Creates new form TelaVersao
     */
    public TelaVersao() {
        initComponents();

        versaoControl = new VersaoControl();

        listaCampoVersao.add(csSistema);
        listaCampoVersao.add(csDescricao);
        listaCampoVersao.add(ciVersaoPrincipal);
        listaCampoVersao.add(ciVersaoSecundaria);
        listaCampoVersao.add(ciVersaoPath);

        otmConsultaVersao.setData(versaoControl.getlConsultaVersao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paVersao = new br.com.martinello.componentesbasicos.paineis.PainelAba();
        pConsulta = new br.com.martinello.componentesbasicos.paineis.Painel();
        jspConsultaVersoes = new javax.swing.JScrollPane();
        tpConsultaVersoes = new br.com.martinello.componentesbasicos.TabelaPadrao();
        jpFiltros = new javax.swing.JPanel();
        rFiltroSistema = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroDescricao = new br.com.martinello.componentesbasicos.Rotulo();
        bIncluir = new br.com.martinello.componentesbasicos.Botao();
        bAlterar = new br.com.martinello.componentesbasicos.Botao();
        bPesquisar = new br.com.martinello.componentesbasicos.Botao();
        bExcluir = new br.com.martinello.componentesbasicos.Botao();
        cscFiltroSistema = new br.com.martinello.componentesbasicos.consulta.CampoStringConsulta();
        cscFiltroDescricao = new br.com.martinello.componentesbasicos.consulta.CampoStringConsulta();
        bImprimir = new br.com.martinello.componentesbasicos.Botao();
        pCadastro = new br.com.martinello.componentesbasicos.paineis.Painel();
        pBotoes = new br.com.martinello.componentesbasicos.paineis.Painel();
        bSalvar = new br.com.martinello.componentesbasicos.Botao();
        bCancelar = new br.com.martinello.componentesbasicos.Botao();
        pCadastroVersao = new br.com.martinello.componentesbasicos.paineis.Painel();
        rSistema = new br.com.martinello.componentesbasicos.Rotulo();
        csSistema = new br.com.martinello.componentesbasicos.CampoString();
        rVersaoPrincipal = new br.com.martinello.componentesbasicos.Rotulo();
        ciVersaoPrincipal = new br.com.martinello.componentesbasicos.CampoInteiro();
        rDescricao = new br.com.martinello.componentesbasicos.Rotulo();
        csDescricao = new br.com.martinello.componentesbasicos.CampoString();
        rVersaoSecundaria = new br.com.martinello.componentesbasicos.Rotulo();
        ciVersaoSecundaria = new br.com.martinello.componentesbasicos.CampoInteiro();
        rVersaoPath = new br.com.martinello.componentesbasicos.Rotulo();
        ciVersaoPath = new br.com.martinello.componentesbasicos.CampoInteiro();
        jpsStatusBar = new br.com.martinello.componentesbasicos.paineis.JPStatus();

        setClosable(true);
        setIconifiable(true);
        setTitle("Controle de Versões");

        pConsulta.setLayout(new java.awt.BorderLayout());

        tpConsultaVersoes.setModel(otmConsultaVersao);
        tpConsultaVersoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpConsultaVersoesMouseClicked(evt);
            }
        });
        jspConsultaVersoes.setViewportView(tpConsultaVersoes);

        pConsulta.add(jspConsultaVersoes, java.awt.BorderLayout.CENTER);

        jpFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ConstantesGlobais.FONTE_11_NORMAL));

        rFiltroSistema.setText("Sistema:");

        rFiltroDescricao.setText("Descrição:");

        bIncluir.setMnemonic('i');
        bIncluir.setText("Incluir");
        bIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIncluirActionPerformed(evt);
            }
        });

        bAlterar.setMnemonic('a');
        bAlterar.setText("Alterar");
        bAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarActionPerformed(evt);
            }
        });

        bPesquisar.setMnemonic('p');
        bPesquisar.setText("Pesquisar");
        bPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisarActionPerformed(evt);
            }
        });

        bExcluir.setMnemonic('e');
        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        bImprimir.setMnemonic('e');
        bImprimir.setText("Imprimir");
        bImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFiltrosLayout = new javax.swing.GroupLayout(jpFiltros);
        jpFiltros.setLayout(jpFiltrosLayout);
        jpFiltrosLayout.setHorizontalGroup(
            jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiltrosLayout.createSequentialGroup()
                .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFiltrosLayout.createSequentialGroup()
                        .addComponent(rFiltroDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cscFiltroDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                    .addGroup(jpFiltrosLayout.createSequentialGroup()
                        .addComponent(rFiltroSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cscFiltroSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFiltrosLayout.createSequentialGroup()
                .addGap(0, 144, Short.MAX_VALUE)
                .addComponent(bPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jpFiltrosLayout.setVerticalGroup(
            jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiltrosLayout.createSequentialGroup()
                .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rFiltroSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cscFiltroSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rFiltroDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cscFiltroDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpFiltrosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rFiltroDescricao, rFiltroSistema});

        pConsulta.add(jpFiltros, java.awt.BorderLayout.PAGE_START);

        paVersao.addTab("Consulta", pConsulta);

        pCadastro.setLayout(new java.awt.BorderLayout());

        pBotoes.setPreferredSize(new java.awt.Dimension(979, 35));

        bSalvar.setMnemonic('s');
        bSalvar.setText("Salvar");
        bSalvar.setPreferredSize(new java.awt.Dimension(84, 23));
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });
        pBotoes.add(bSalvar);

        bCancelar.setMnemonic('c');
        bCancelar.setText("Cancelar");
        bCancelar.setPreferredSize(new java.awt.Dimension(84, 23));
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        pBotoes.add(bCancelar);

        pCadastro.add(pBotoes, java.awt.BorderLayout.SOUTH);

        csSistema.setComponenteRotulo(rSistema);
        csSistema.setDescricaoRotulo("Sistema");
        csSistema.setObrigatorio(true);

        ciVersaoPrincipal.setText("0");
        ciVersaoPrincipal.setComponenteRotulo(rVersaoPrincipal);
        ciVersaoPrincipal.setDescricaoRotulo("Versão Principal");

        csDescricao.setComponenteRotulo(rDescricao);
        csDescricao.setDescricaoRotulo("Descrição");
        csDescricao.setObrigatorio(true);

        ciVersaoSecundaria.setText("0");
        ciVersaoSecundaria.setComponenteRotulo(rVersaoSecundaria);
        ciVersaoSecundaria.setDescricaoRotulo("Versão Secundária");

        ciVersaoPath.setText("0");
        ciVersaoPath.setComponenteRotulo(rVersaoPath);
        ciVersaoPath.setDescricaoRotulo("Versão Path");

        javax.swing.GroupLayout pCadastroVersaoLayout = new javax.swing.GroupLayout(pCadastroVersao);
        pCadastroVersao.setLayout(pCadastroVersaoLayout);
        pCadastroVersaoLayout.setHorizontalGroup(
            pCadastroVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroVersaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastroVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroVersaoLayout.createSequentialGroup()
                        .addComponent(rSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCadastroVersaoLayout.createSequentialGroup()
                        .addComponent(rVersaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ciVersaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCadastroVersaoLayout.createSequentialGroup()
                        .addComponent(rVersaoSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ciVersaoSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCadastroVersaoLayout.createSequentialGroup()
                        .addComponent(rVersaoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ciVersaoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCadastroVersaoLayout.createSequentialGroup()
                        .addComponent(rDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );

        pCadastroVersaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rDescricao, rSistema, rVersaoPath, rVersaoPrincipal, rVersaoSecundaria});

        pCadastroVersaoLayout.setVerticalGroup(
            pCadastroVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroVersaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastroVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rVersaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciVersaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rVersaoSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciVersaoSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rVersaoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciVersaoPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pCadastroVersaoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rDescricao, rSistema, rVersaoPath, rVersaoPrincipal, rVersaoSecundaria});

        pCadastro.add(pCadastroVersao, java.awt.BorderLayout.CENTER);

        paVersao.addTab("Cadastro/Alteração", pCadastro);

        getContentPane().add(paVersao, java.awt.BorderLayout.CENTER);
        getContentPane().add(jpsStatusBar, java.awt.BorderLayout.PAGE_END);

        setBounds(0, 0, 761, 472);
    }// </editor-fold>//GEN-END:initComponents

    private void bIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIncluirActionPerformed
        versaoControl.novo();
        statusTela = INCLUINDO;
        habilitaComponentesCadastro(true);
        habilitaCadastro(true);
        habilitaBotoesColunas(true);

    }//GEN-LAST:event_bIncluirActionPerformed

    private void bAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarActionPerformed
        alterarVersao();
    }//GEN-LAST:event_bAlterarActionPerformed

    private void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarActionPerformed
        List<Filtro> lFiltros = new LinkedList<>();
        lFiltros.add(cscFiltroSistema.getFiltro("sistema"));
        lFiltros.add(cscFiltroDescricao.getFiltro("descricao"));

        try {
            versaoControl.pesquisar(lFiltros);

            otmConsultaVersao.fireTableDataChanged();

            tpConsultaVersoes.packAll();
        } catch (ErroSistemaException ex) {
            jpsStatusBar.setStatus("Erro ao pesquisar versão." + ex.getLocalizedMessage(), JPStatus.ALERTA, ex);
        }
    }//GEN-LAST:event_bPesquisarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        if (tpConsultaVersoes.getSelectedRow() >= 0) {
            try {
                versaoControl.setVersao(versaoControl.find(otmConsultaVersao.getValue(tpConsultaVersoes.getLinhaSelecionada())));

                carregarDadosVersao();

                habilitaComponentesCadastro(false);

                bSalvar.setEnabled(true);
                bCancelar.setEnabled(true);

                habilitaCadastro(true);

                statusTela = EXCLUINDO;
            } catch (ErroSistemaException ex) {
                jpsStatusBar.setStatus("Erro ao selecionar versão.", JPStatus.ERRO);
            }
        } else {
            jpsStatusBar.setStatus("É necessário selecionar uma versão.", JPStatus.ALERTA);
        }
    }//GEN-LAST:event_bExcluirActionPerformed

    private void bImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImprimirActionPerformed

    }//GEN-LAST:event_bImprimirActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        try {
            if (statusTela == INCLUINDO || statusTela == ALTERANDO) {
                if (!validarListaCampos(listaCampoVersao)) {
                    jpsStatusBar.setStatus("Campos obrigatórios não preenchidos.", JPStatus.ALERTA);
                    return;
                }

                setarDadosVersao();

                versaoControl.salvar();

                otmConsultaVersao.fireTableDataChanged();

                int posicaoLinha = versaoControl.getlConsultaVersao().indexOf(versaoControl.getVersao());
                tpConsultaVersoes.addRowSelectionInterval(tpConsultaVersoes.convertRowIndexToView(posicaoLinha), tpConsultaVersoes.convertRowIndexToView(posicaoLinha));
                tpConsultaVersoes.scrollRectToVisible(tpConsultaVersoes.getCellRect(tpConsultaVersoes.getSelectedRow(), 0, true));

            } else {
                versaoControl.excluir();

                otmConsultaVersao.fireTableDataChanged();
            }

            jpsStatusBar.setStatus("Processamento efetuado com sucesso.", JPStatus.NORMAL);
            habilitaCadastro(false);

            limparListaCampos(listaCampoVersao);

            statusTela = INDEFINIDO;

        } catch (ErroSistemaException ex) {
            jpsStatusBar.setStatus(ex.getLocalizedMessage(), JPStatus.ALERTA);
        }
    }//GEN-LAST:event_bSalvarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        habilitaCadastro(false);
        statusTela = INDEFINIDO;
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tpConsultaVersoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpConsultaVersoesMouseClicked
        if (evt.getClickCount() == 2) {
            alterarVersao();
        }
    }//GEN-LAST:event_tpConsultaVersoesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Botao bAlterar;
    private br.com.martinello.componentesbasicos.Botao bCancelar;
    private br.com.martinello.componentesbasicos.Botao bExcluir;
    private br.com.martinello.componentesbasicos.Botao bImprimir;
    private br.com.martinello.componentesbasicos.Botao bIncluir;
    private br.com.martinello.componentesbasicos.Botao bPesquisar;
    private br.com.martinello.componentesbasicos.Botao bSalvar;
    private br.com.martinello.componentesbasicos.CampoInteiro ciVersaoPath;
    private br.com.martinello.componentesbasicos.CampoInteiro ciVersaoPrincipal;
    private br.com.martinello.componentesbasicos.CampoInteiro ciVersaoSecundaria;
    private br.com.martinello.componentesbasicos.CampoString csDescricao;
    private br.com.martinello.componentesbasicos.CampoString csSistema;
    private br.com.martinello.componentesbasicos.consulta.CampoStringConsulta cscFiltroDescricao;
    private br.com.martinello.componentesbasicos.consulta.CampoStringConsulta cscFiltroSistema;
    private javax.swing.JPanel jpFiltros;
    private br.com.martinello.componentesbasicos.paineis.JPStatus jpsStatusBar;
    private javax.swing.JScrollPane jspConsultaVersoes;
    private br.com.martinello.componentesbasicos.paineis.Painel pBotoes;
    private br.com.martinello.componentesbasicos.paineis.Painel pCadastro;
    private br.com.martinello.componentesbasicos.paineis.Painel pCadastroVersao;
    private br.com.martinello.componentesbasicos.paineis.Painel pConsulta;
    private br.com.martinello.componentesbasicos.paineis.PainelAba paVersao;
    private br.com.martinello.componentesbasicos.Rotulo rDescricao;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroDescricao;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroSistema;
    private br.com.martinello.componentesbasicos.Rotulo rSistema;
    private br.com.martinello.componentesbasicos.Rotulo rVersaoPath;
    private br.com.martinello.componentesbasicos.Rotulo rVersaoPrincipal;
    private br.com.martinello.componentesbasicos.Rotulo rVersaoSecundaria;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpConsultaVersoes;
    // End of variables declaration//GEN-END:variables

    public void alterarVersao() {
        if (tpConsultaVersoes.getSelectedRow() >= 0) {
            try {
                versaoControl.setVersao(versaoControl.find(otmConsultaVersao.getValue(tpConsultaVersoes.getLinhaSelecionada())));

                carregarDadosVersao();

                habilitaComponentesCadastro(true);
                habilitaCadastro(true);
                habilitaBotoesColunas(true);

                statusTela = ALTERANDO;
            } catch (ErroSistemaException ex) {
                jpsStatusBar.setStatus("Erro ao selecionar a versão.", JPStatus.ERRO);
            }
        } else {
            jpsStatusBar.setStatus("É necessário selecionar uma versão.", JPStatus.ALERTA);
        }
    }

    public void carregarDadosVersao() {
        csSistema.setString(versaoControl.getVersao().getSistema());
        csDescricao.setString(versaoControl.getVersao().getDescricao());
        ciVersaoPrincipal.setLong(versaoControl.getVersao().getVersaoPrincipal());
        ciVersaoSecundaria.setLong(versaoControl.getVersao().getVersaoSecundaria());
        ciVersaoPath.setLong(versaoControl.getVersao().getVersaoPath());
    }

    public void setarDadosVersao() {
        versaoControl.getVersao().setSistema(csSistema.getString());
        versaoControl.getVersao().setDescricao(csDescricao.getString());
        versaoControl.getVersao().setVersaoPrincipal(ciVersaoPrincipal.getLong());
        versaoControl.getVersao().setVersaoSecundaria(ciVersaoSecundaria.getLong());
        versaoControl.getVersao().setVersaoPath(ciVersaoPath.getLong());
    }

    @Override
    public void habilitaCadastro(boolean habilitada) {
        paVersao.setEnabledAt(0, !habilitada);
        paVersao.setEnabledAt(1, habilitada);
        paVersao.setSelectedIndex(habilitada ? 1 : 0);
    }

}
