/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.gerenciador.view;

import br.com.martinello.bd.matriz.control.DicionarioControl;
import br.com.martinello.componentesbasicos.paineis.JPStatus;
import br.com.martinello.util.excessoes.ErroSistemaException;

/**
 *
 * @author sidnei.vieira
 */
public class TelaGeracaoDicionario extends TelaPadrao {

    private DicionarioControl dicionarioControl;

    /**
     * Creates new form TelaGeracaoDicionario
     */
    public TelaGeracaoDicionario() {
        initComponents();

        dicionarioControl = new DicionarioControl();
        dicionarioControl.setjProgressBar(jProgressBar);
        dicionarioControl.setrStatus(rStatus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pGeracao = new br.com.martinello.componentesbasicos.paineis.Painel();
        jProgressBar = new javax.swing.JProgressBar();
        bGerar = new br.com.martinello.componentesbasicos.Botao();
        rStatus = new br.com.martinello.componentesbasicos.Rotulo();
        jpsStatus = new br.com.martinello.componentesbasicos.paineis.JPStatus();

        setClosable(true);
        setIconifiable(true);
        setTitle("Geração de Dicionário de Dados");

        jProgressBar.setStringPainted(true);

        bGerar.setText("Gerar");
        bGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGerarActionPerformed(evt);
            }
        });

        rStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rStatus.setText(" ");

        javax.swing.GroupLayout pGeracaoLayout = new javax.swing.GroupLayout(pGeracao);
        pGeracao.setLayout(pGeracaoLayout);
        pGeracaoLayout.setHorizontalGroup(
            pGeracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGeracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGeracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(pGeracaoLayout.createSequentialGroup()
                        .addComponent(bGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pGeracaoLayout.setVerticalGroup(
            pGeracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGeracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pGeracao, java.awt.BorderLayout.CENTER);
        getContentPane().add(jpsStatus, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGerarActionPerformed
        new Thread() {

            @Override
            public void run() {
                try {
                    bGerar.setEnabled(false);
                    dicionarioControl.gerarDicionarioDados();

                    jpsStatus.setStatus("Dicionário de Dagos Gerado com sucesso!", JPStatus.NORMAL);
                } catch (ErroSistemaException ex) {
                    jpsStatus.setStatus("Erro ao gerar." + ex.getLocalizedMessage(), JPStatus.ERRO, ex);
                } finally {
                    bGerar.setEnabled(true);
                }
            }
        }.start();


    }//GEN-LAST:event_bGerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Botao bGerar;
    private javax.swing.JProgressBar jProgressBar;
    private br.com.martinello.componentesbasicos.paineis.JPStatus jpsStatus;
    private br.com.martinello.componentesbasicos.paineis.Painel pGeracao;
    private br.com.martinello.componentesbasicos.Rotulo rStatus;
    // End of variables declaration//GEN-END:variables
}
