/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.cadastro.view.paineis;

import br.com.martinello.matriz.bd.control.ProdutoControl;
import br.com.martinello.matriz.bd.model.domain.Produto;
import br.com.martinello.matriz.componentesbasicos.ConstantesGlobais;
import br.com.martinello.matriz.componentesbasicos.TabelaPadrao;
import br.com.martinello.matriz.componentesbasicos.paineis.JPStatus;
import br.com.martinello.matriz.util.excessoes.ErroSistemaException;
import com.towel.swing.table.ObjectTableModel;
import java.util.LinkedList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author luiz.almeida
 */
public class PainelE075PRO extends javax.swing.JPanel {

    /**
     * Creates new form PainelE075PRO
     */
    private List<Produto> lProduto;
    private ProdutoControl produtoControl;
    protected JPStatus jpsStatus;
    private final ObjectTableModel<Produto> otmE075PRO = new ObjectTableModel<>(Produto.class, "codigo,descricao,dataCadastro,estoque,nomeUsuario");

    public PainelE075PRO() {

    }

    public PainelE075PRO(List<Produto> lProdutos) {
        initComponents();
        tpE075Pro.setModel(otmE075PRO);
        tpE075Pro.getSelectionModel().addListSelectionListener((ListSelectionEvent evt) -> {
            if (evt.getValueIsAdjusting()) {
                return;
            }
            if (tpE075Pro.getSelectedRow() >= 0) {
            }
        });

        setFont(ConstantesGlobais.FONTE_11_NORMAL);
        //csFiltroMarca.setJlDescricao(rDescricaoMarca);

        if (lProdutos != null) {
            otmE075PRO.setData(lProdutos);
            otmE075PRO.fireTableDataChanged();
            tpE075Pro.packAll();
        }
            carregarE075Pro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPE075Pro = new javax.swing.JPanel();
        ppE075ProTb = new br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao();
        jspTabE075Pro = new javax.swing.JScrollPane();
        tpE075Pro = new br.com.martinello.matriz.componentesbasicos.TabelaPadrao();

        setLayout(new java.awt.BorderLayout());

        jPE075Pro.setLayout(new java.awt.BorderLayout());

        ppE075ProTb.setLayout(new java.awt.BorderLayout());

        jspTabE075Pro.setOpaque(false);
        jspTabE075Pro.setPreferredSize(new java.awt.Dimension(600, 362));

        tpE075Pro.setModel(otmE075PRO);
        tpE075Pro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpE075ProKeyPressed(evt);
            }
        });
        jspTabE075Pro.setViewportView(tpE075Pro);

        ppE075ProTb.add(jspTabE075Pro, java.awt.BorderLayout.CENTER);

        jPE075Pro.add(ppE075ProTb, java.awt.BorderLayout.CENTER);

        add(jPE075Pro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tpE075ProKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpE075ProKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpE075ProKeyPressed
    public void carregarE075Pro() {

        try {
            produtoControl = new ProdutoControl();
            lProduto = new LinkedList<>();
            System.out.println("Passei aqui");
            lProduto = produtoControl.buscarPendecias();
            if (lProduto != null) {
                otmE075PRO.setData(lProduto);
                otmE075PRO.fireTableDataChanged();
                tpE075Pro.packAll();
            }
        } catch (ErroSistemaException ex) {
            jpsStatus.setStatus("Erro ao consultar produtos", JPStatus.ERRO, ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPE075Pro;
    private javax.swing.JScrollPane jspTabE075Pro;
    private br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao ppE075ProTb;
    private br.com.martinello.matriz.componentesbasicos.TabelaPadrao tpE075Pro;
    // End of variables declaration//GEN-END:variables

    public TabelaPadrao getTpE075Pro() {
        return tpE075Pro;
    }

    public void setTpProdutos(TabelaPadrao tpE075Pro) {
        this.tpE075Pro = tpE075Pro;
    }

    public void setJpsStatus(JPStatus jpsStatus) {
        this.jpsStatus = jpsStatus;
    }

    public void setaFocoTabelaConsulta() {
        java.awt.EventQueue.invokeLater(() -> {
            tpE075Pro.grabFocus();
            if (tpE075Pro.getRowCount() > 0) {
                tpE075Pro.addRowSelectionInterval(0, 0);
            }
        });
    }
}
