/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.matriz.componentesbasicos.paineis;

import br.com.martinello.matriz.componentesbasicos.ConstantesGlobais;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import javax.swing.Timer;
import org.jdesktop.swingx.JXErrorPane;
import org.jdesktop.swingx.error.ErrorInfo;

/**
 *
 * @author Sidnei
 */
public class JPStatus extends javax.swing.JPanel {

    public static final String ALERTA = "ALERTA";
    public static final String ERRO = "ERRO";
    public static final String NORMAL = "NORMAL";

    private String statusAtual = NORMAL;
    private Exception excecao = null;

    /**
     * Creates new form JPStatus
     */
    public JPStatus() {
        initComponents();
        jxlStatus.setFont(ConstantesGlobais.FONTE_11_BOLD);
    }

    public void setStatus(String mensagem, String tipo, Exception excecao) {
        setStatus(mensagem, tipo);
        this.excecao = excecao;
    }

    public void setStatus(String mensagem, String tipo) {
        setStatus(mensagem, tipo, 0);
    }

    public void setStatus(String mensagem, String tipo, int tempoLimpar) {
        if (tipo.equals(NORMAL)) {
            statusAtual = tipo;
            jxlStatus.setForeground(Color.BLACK);
            jxlStatus.setText(mensagem);
        } else if (tipo.equals(ERRO)) {
            jxlStatus.setForeground(Color.RED);
            jxlStatus.setText(mensagem);
            statusAtual = tipo;
        } else if (tipo.equals(ALERTA)) {
            jxlStatus.setForeground(Color.BLUE);
            jxlStatus.setText(mensagem);
            statusAtual = tipo;
        }

        if (tempoLimpar != 0) {
            final Timer tempo = new Timer(tempoLimpar * 1000, (ActionEvent e) -> {
                limparStatus();
            }
            );
            tempo.start();
        }

    }

    public void limparStatus() {
        jxlStatus.setForeground(Color.BLACK);
        jxlStatus.setText("");
        excecao = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jxlStatus = new org.jdesktop.swingx.JXLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jxlStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jxlStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jxlStatusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jxlStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jxlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jxlStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jxlStatusMouseClicked
        if (statusAtual.equals(ERRO) && excecao != null) {
            ErrorInfo info = new ErrorInfo(jxlStatus.getText(), excecao.getMessage(), null, "erro", excecao, Level.ALL, null);
            JXErrorPane.showDialog(null, info);
        }

    }//GEN-LAST:event_jxlStatusMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel jxlStatus;
    // End of variables declaration//GEN-END:variables
}
