package br.com.martinello.cadastro.view.consultas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import br.com.martinello.cadastro.componentes.consulta.CampoConsultaProduto;
import br.com.martinello.cadastro.view.paineis.PainelProduto;
import br.com.martinello.matriz.bd.model.domain.Produto;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;

/**
 *
 * @author Sidnei
 */
public class TelaConsultaProdutosModal extends javax.swing.JDialog {

    protected PainelProduto painelProduto;
    protected CampoConsultaProduto campoConsultaProduto;
    

    /**
     * Creates new form TelaConsultaProduto
     *
     * @param parent
     * @param modal
     * @param campoConsultaProduto
     * @param lProdutos
     */
    public TelaConsultaProdutosModal(java.awt.Frame parent, boolean modal, CampoConsultaProduto campoConsultaProduto, List<Produto> lProdutos) {
        super(parent, modal);

        this.campoConsultaProduto = campoConsultaProduto;

        initComponents();

        painelProduto = new PainelProduto(lProdutos);
        painelProduto.setJpsStatus(jpsStatus);
        getContentPane().add(painelProduto, java.awt.BorderLayout.CENTER);

        InputMap im = painelProduto.getTpProdutos().getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        KeyStroke enter = KeyStroke.getKeyStroke("ENTER");
        im.put(enter, im.get(KeyStroke.getKeyStroke(KeyEvent.VK_GREATER, 0)));
        Action enterAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selecionar();
            }
        };
        painelProduto.getTpProdutos().getActionMap().put(im.get(enter), enterAction);
        JRootPane meurootpane = getRootPane();
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meurootpane.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInferior = new br.com.martinello.matriz.componentesbasicos.paineis.Painel();
        jpsStatus = new br.com.martinello.matriz.componentesbasicos.paineis.JPStatus();
        pBotoes = new br.com.martinello.matriz.componentesbasicos.paineis.Painel();
        bSelecionar = new br.com.martinello.matriz.componentesbasicos.Botao();
        bCancelar = new br.com.martinello.matriz.componentesbasicos.Botao();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setUndecorated(true);

        pInferior.setLayout(new java.awt.BorderLayout());
        pInferior.add(jpsStatus, java.awt.BorderLayout.CENTER);

        pBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bSelecionar.setMnemonic('s');
        bSelecionar.setText("Selecionar");
        bSelecionar.setPreferredSize(new java.awt.Dimension(93, 22));
        bSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelecionarActionPerformed(evt);
            }
        });
        pBotoes.add(bSelecionar);

        bCancelar.setMnemonic('c');
        bCancelar.setText("Cancelar");
        bCancelar.setPreferredSize(new java.awt.Dimension(93, 22));
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        pBotoes.add(bCancelar);

        pInferior.add(pBotoes, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pInferior, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelecionarActionPerformed
        selecionar();
    }//GEN-LAST:event_bSelecionarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProdutosModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProdutosModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProdutosModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProdutosModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaConsultaProdutosModal dialog = new TelaConsultaProdutosModal(new javax.swing.JFrame(), true, null, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setSize(1150, 700);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.matriz.componentesbasicos.Botao bCancelar;
    private br.com.martinello.matriz.componentesbasicos.Botao bSelecionar;
    private br.com.martinello.matriz.componentesbasicos.paineis.JPStatus jpsStatus;
    private br.com.martinello.matriz.componentesbasicos.paineis.Painel pBotoes;
    private br.com.martinello.matriz.componentesbasicos.paineis.Painel pInferior;
    // End of variables declaration//GEN-END:variables

    public PainelProduto getPainelProduto() {
        return painelProduto;
    }

    public void setPainelProduto(PainelProduto painelProduto) {
        this.painelProduto = painelProduto;
    }

    private void selecionar() {
        campoConsultaProduto.setProduto(painelProduto.getProdutoSelecionado());
        dispose();
    }

}
