package br.com.martinello.cadastro.view.consultas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import br.com.martinello.cadastro.BarraStatus;
import br.com.martinello.cadastro.componentes.consulta.CampoConsultaProduto;
import br.com.martinello.cadastro.view.paineis.PainelE075PRO;
import br.com.martinello.cadastro.view.paineis.PainelProduto;
import br.com.martinello.matriz.bd.model.domain.Produto;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;

/**
 *
 * @author Sidnei
 */
public class TelaConsultaE075Modal extends javax.swing.JDialog {

    protected PainelProduto painelProduto;
    protected CampoConsultaProduto campoConsultaProduto;
    protected PainelE075PRO painelE075PRO;
    protected BarraStatus barraStatus;

    /**
     * Creates new form TelaConsultaProduto
     *
     * @param parent
     * @param modal
     * @param campoConsultaProduto
     * @param lProdutos
     */
    public TelaConsultaE075Modal(java.awt.Frame parent, boolean modal, BarraStatus barraStatus, List<Produto> lProdutos) {
        super(parent, modal);

        this.barraStatus = barraStatus;
        initComponents();

        painelE075PRO = new PainelE075PRO(lProdutos);
        painelE075PRO.setJpsStatus(jpsStatus);
        getContentPane().add(painelE075PRO, java.awt.BorderLayout.CENTER);

        InputMap im = painelE075PRO.getTpE075Pro().getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        KeyStroke enter = KeyStroke.getKeyStroke("ENTER");
        im.put(enter, im.get(KeyStroke.getKeyStroke(KeyEvent.VK_GREATER, 0)));
        Action enterAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        };
        painelE075PRO.getTpE075Pro().getActionMap().put(im.get(enter), enterAction);
        JRootPane meurootpane = getRootPane();
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meurootpane.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInferior = new br.com.martinello.matriz.componentesbasicos.paineis.Painel();
        jpsStatus = new br.com.martinello.matriz.componentesbasicos.paineis.JPStatus();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setUndecorated(true);

        pInferior.setLayout(new java.awt.BorderLayout());
        pInferior.add(jpsStatus, java.awt.BorderLayout.CENTER);

        getContentPane().add(pInferior, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaE075Modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaE075Modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaE075Modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaE075Modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaConsultaE075Modal dialog = new TelaConsultaE075Modal(new javax.swing.JFrame(), true, null, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setSize(1150, 700);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.matriz.componentesbasicos.paineis.JPStatus jpsStatus;
    private br.com.martinello.matriz.componentesbasicos.paineis.Painel pInferior;
    // End of variables declaration//GEN-END:variables

    public void setPainelProduto(PainelProduto painelProduto) {
        this.painelProduto = painelProduto;
    }

    private void selecionar() {
        campoConsultaProduto.setProduto(painelProduto.getProdutoSelecionado());
        dispose();
    }

    public PainelE075PRO getPainelProduto() {
        return painelE075PRO;
    }
}
