/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.cadastro;

import br.com.martinello.cadastro.view.consultas.TelaConsultaE075Modal;
import br.com.martinello.matriz.bd.model.domain.Produto;
import br.com.martinello.matriz.bd.model.domain.Usuario;
import br.com.martinello.matriz.componentesbasicos.ConstantesGlobais;
import br.com.martinello.matriz.util.Utilitarios;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

public class BarraStatus extends javax.swing.JPanel {

    protected Usuario usuarioModel;
    private Date dataExtrator;
    private String status;
    private String filial;
    private int pendencia;
    private List<Produto> lProduto = new LinkedList<>();
            

    public BarraStatus() {
        initComponents();
    }

    public BarraStatus(Usuario usuario, String eletromóveis_martinello, String status, Date dataExtrator, int pendente) {

        initComponents();
        setUsuario(usuario);
        setFilial("Eletromóveis_Martinello");
        setDataExtrator(dataExtrator);
        setStatus(status);
        setPendencia(pendente);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rRotuloLoja = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rLoja = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rRotuloUsuario = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rUsuario = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rRotuloData = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rData = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rRotuloStatus = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rStatus = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rRotuloPendencia = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rPendencia = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        bPendencia = new br.com.martinello.matriz.componentesbasicos.Botao();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rRotuloLoja.setText("LOJA:");
        rRotuloLoja.setFont(ConstantesGlobais.FONTE_11_BOLD);

        rLoja.setForeground(new java.awt.Color(255, 0, 0));
        rLoja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rLoja.setText("jLabel2");
        rLoja.setFont(ConstantesGlobais.FONTE_11_BOLD);

        rRotuloUsuario.setText("USUÁRIO:");
        rRotuloUsuario.setFont(ConstantesGlobais.FONTE_11_BOLD);

        rUsuario.setForeground(new java.awt.Color(255, 0, 0));
        rUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rUsuario.setText("jLabel4");
        rUsuario.setFont(ConstantesGlobais.FONTE_11_BOLD);

        rRotuloData.setText("DATA ");
        rRotuloData.setFont(ConstantesGlobais.FONTE_11_BOLD);

        rData.setForeground(new java.awt.Color(255, 0, 0));
        rData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rData.setText("jLabel4");
        rData.setFont(ConstantesGlobais.FONTE_11_BOLD);

        rRotuloStatus.setText("STATUS:");
        rRotuloStatus.setFont(ConstantesGlobais.FONTE_11_BOLD);

        rStatus.setForeground(new java.awt.Color(255, 0, 0));
        rStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rStatus.setFont(ConstantesGlobais.FONTE_11_BOLD);
        rStatus.setText("jLabel3");

        rRotuloPendencia.setText("PENDENCIAS:");
        rRotuloPendencia.setFont(ConstantesGlobais.FONTE_11_BOLD);

        rPendencia.setForeground(new java.awt.Color(255, 0, 0));
        rPendencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rPendencia.setFont(ConstantesGlobais.FONTE_11_BOLD);
        rPendencia.setText("jLabel5");
        rPendencia.addMouseListener(
                new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent arg0
            ) {
                java.awt.EventQueue.invokeLater(() -> {
                    abreTelaConsulta(lProduto);
                    
                }
                );
            }
        }
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(rRotuloLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rRotuloUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rRotuloStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(rRotuloPendencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rPendencia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(rRotuloData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rRotuloData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rRotuloLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rRotuloUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rRotuloStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rRotuloPendencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rPendencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.matriz.componentesbasicos.Rotulo rData;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rLoja;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rRotuloData;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rRotuloLoja;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rRotuloStatus;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rRotuloUsuario;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rStatus;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rUsuario;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rPendencia;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rRotuloPendencia;
    private br.com.martinello.matriz.componentesbasicos.Botao bPendencia;
    // End of variables declaration//GEN-END:variables

    public Usuario getUsuario() {
        return usuarioModel;
    }

    public void setUsuario(Usuario usuario) {
        this.usuarioModel = usuario;

        rUsuario.setText(usuarioModel != null ? usuarioModel.getLogin() : "");
    }

    public void setFilial(String filial) {
        this.filial = filial;

        rLoja.setText(filial);
    }

    public Date getDataExtrator() {
        return dataExtrator;
    }

    public void setDataExtrator(Date dataExtrator) {
        this.dataExtrator = dataExtrator;
        rData.setText(Utilitarios.dataParaString(dataExtrator));

    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
        rStatus.setText(status);
    }

    /**
     * @return the pendencia
     */
    public int getPendencia() {
        return pendencia;
    }

    /**
     * @param pendencia the pendencia to set
     */
    public void setPendencia(int pendencia) {
        this.pendencia = pendencia;
        rPendencia.setText(String.valueOf(pendencia));
    }
    private void abreTelaConsulta(List<Produto> lProdutos) {
        java.awt.EventQueue.invokeLater(() -> {
            TelaConsultaE075Modal telaConsultaProduto = new TelaConsultaE075Modal(new javax.swing.JFrame(), true, this, lProdutos);
            telaConsultaProduto.setSize(1150, 700);
            telaConsultaProduto.setLocationRelativeTo(null);      

            telaConsultaProduto.getPainelProduto().setaFocoTabelaConsulta();

            telaConsultaProduto.setVisible(true);
          

        });
    }

}
