/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.cadastro.view;

import br.com.martinello.matriz.bd.control.CategoriaControl;
import br.com.martinello.matriz.bd.model.domain.Categoria;
import br.com.martinello.matriz.bd.model.domain.Usuario;
import br.com.martinello.matriz.componentesbasicos.paineis.JPStatus;
import br.com.martinello.matriz.componentesbasicos.view.TelaPadrao;
import br.com.martinello.matriz.util.FixedLengthDocument;
import br.com.martinello.matriz.util.excessoes.ErroSistemaException;
import com.towel.swing.table.ObjectTableModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz.almeida
 */
public class TelaCategoria extends TelaPadrao {

    /**
     * Creates new form TelaCategoria
     */
    private Categoria filtroCategoria;
    private Categoria categoria;
    private CategoriaControl categoriaControl;
    private List<Categoria> lCategoria;
    private boolean resultado;
    private String salvarAlterar = "Salvar";
    private static Usuario usuario;
    private final ObjectTableModel<Categoria> otmCategoria = new ObjectTableModel<>(Categoria.class, "idCategoria,categoria,situacao,obsCategoria,idUsuario,nomeUsuario,dataCadastro");

    public TelaCategoria() {
        initComponents();
        paCategoria.setEnabledAt(1, false);
       usuario = (TelaPrincipal.usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpsCategoria = new br.com.martinello.matriz.componentesbasicos.paineis.JPStatus();
        paCategoria = new br.com.martinello.matriz.componentesbasicos.paineis.PainelAba();
        ppConsultaCat = new br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao();
        ppTabConsultaCat = new br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao();
        jspTabConsultaCat = new javax.swing.JScrollPane();
        tpConsultaCat = new br.com.martinello.matriz.componentesbasicos.TabelaPadrao();
        ppFiltroConsultaCat = new br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao();
        rotulo1 = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rotulo2 = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        ciIdCategoria = new br.com.martinello.matriz.componentesbasicos.CampoInteiro();
        cscCategoria = new br.com.martinello.matriz.componentesbasicos.consulta.CampoStringConsulta();
        rotulo3 = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        jrbAtivoCatFiltro = new javax.swing.JRadioButton();
        jrbInativoCatFiltro = new javax.swing.JRadioButton();
        btPesquisar = new br.com.martinello.matriz.componentesbasicos.Botao();
        btAlterar = new br.com.martinello.matriz.componentesbasicos.Botao();
        btCadastrar = new br.com.martinello.matriz.componentesbasicos.Botao();
        btExcluir = new br.com.martinello.matriz.componentesbasicos.Botao();
        ppCadastroCat = new br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao();
        ppFiltroConsultaCat1 = new br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao();
        rotulo4 = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        rotulo5 = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        ciIdCategoriaCad = new br.com.martinello.matriz.componentesbasicos.CampoInteiro();
        rotulo6 = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        btCancelarCadastro = new br.com.martinello.matriz.componentesbasicos.Botao();
        btSalvarCadastro = new br.com.martinello.matriz.componentesbasicos.Botao();
        rotulo7 = new br.com.martinello.matriz.componentesbasicos.Rotulo();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaObservacao = new javax.swing.JTextArea();
        csCategoriaCad = new br.com.martinello.matriz.componentesbasicos.CampoString();
        clsSituacaoCad = new br.com.martinello.matriz.componentesbasicos.CampoListaSimples();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Categoria");
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().add(jpsCategoria, java.awt.BorderLayout.SOUTH);

        paCategoria.setToolTipText("");

        ppConsultaCat.setLayout(new java.awt.BorderLayout());

        ppTabConsultaCat.setMinimumSize(new java.awt.Dimension(1029, 120));
        ppTabConsultaCat.setPreferredSize(new java.awt.Dimension(1029, 480));
        ppTabConsultaCat.setLayout(new java.awt.BorderLayout());

        tpConsultaCat.setModel(otmCategoria);
        tpConsultaCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpConsultaCatKeyPressed(evt);
            }
        });
        jspTabConsultaCat.setViewportView(tpConsultaCat);

        ppTabConsultaCat.add(jspTabConsultaCat, java.awt.BorderLayout.CENTER);

        ppConsultaCat.add(ppTabConsultaCat, java.awt.BorderLayout.CENTER);

        ppFiltroConsultaCat.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros da pesquisa"));
        ppFiltroConsultaCat.setMinimumSize(new java.awt.Dimension(1029, 120));
        ppFiltroConsultaCat.setPreferredSize(new java.awt.Dimension(1029, 120));

        rotulo1.setText("Id.:");

        rotulo2.setText("Categoria:");
        rotulo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotulo2MouseClicked(evt);
            }
        });

        ciIdCategoria.setEditable(false);
        ciIdCategoria.setText("0");

        cscCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cscCategoriaMouseClicked(evt);
            }
        });

        rotulo3.setText("Status:");

        jrbAtivoCatFiltro.setText("Ativo");

        jrbInativoCatFiltro.setText("Inativo");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btCadastrar.setText("Incluir");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ppFiltroConsultaCatLayout = new javax.swing.GroupLayout(ppFiltroConsultaCat);
        ppFiltroConsultaCat.setLayout(ppFiltroConsultaCatLayout);
        ppFiltroConsultaCatLayout.setHorizontalGroup(
            ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroConsultaCatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppFiltroConsultaCatLayout.createSequentialGroup()
                        .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rotulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cscCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ppFiltroConsultaCatLayout.createSequentialGroup()
                                .addComponent(jrbAtivoCatFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbInativoCatFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ppFiltroConsultaCatLayout.createSequentialGroup()
                        .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ciIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 842, Short.MAX_VALUE)
                .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ppFiltroConsultaCatLayout.createSequentialGroup()
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        ppFiltroConsultaCatLayout.setVerticalGroup(
            ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroConsultaCatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rotulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cscCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ppFiltroConsultaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rotulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jrbAtivoCatFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jrbInativoCatFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ppConsultaCat.add(ppFiltroConsultaCat, java.awt.BorderLayout.NORTH);

        paCategoria.addTab("Consulta", ppConsultaCat);

        ppCadastroCat.setMaximumSize(new java.awt.Dimension(1024, 500));
        ppCadastroCat.setLayout(new java.awt.BorderLayout());

        ppFiltroConsultaCat1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros da pesquisa"));
        ppFiltroConsultaCat1.setMinimumSize(new java.awt.Dimension(1029, 170));
        ppFiltroConsultaCat1.setPreferredSize(new java.awt.Dimension(1029, 170));

        rotulo4.setText("Id.:");

        rotulo5.setText("Categoria:");

        ciIdCategoriaCad.setEditable(false);
        ciIdCategoriaCad.setText("0");

        rotulo6.setText("Status:");

        btCancelarCadastro.setText("Cancelar");
        btCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCadastroActionPerformed(evt);
            }
        });

        btSalvarCadastro.setText("Salvar");
        btSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCadastroActionPerformed(evt);
            }
        });

        rotulo7.setText("Observação:");

        jtaObservacao.setColumns(20);
        jtaObservacao.setDocument(new FixedLengthDocument(150));
        jtaObservacao.setRows(5);
        jScrollPane2.setViewportView(jtaObservacao);

        csCategoriaCad.setQtdMaxCaracteres(125);

        clsSituacaoCad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo", "" }));

        javax.swing.GroupLayout ppFiltroConsultaCat1Layout = new javax.swing.GroupLayout(ppFiltroConsultaCat1);
        ppFiltroConsultaCat1.setLayout(ppFiltroConsultaCat1Layout);
        ppFiltroConsultaCat1Layout.setHorizontalGroup(
            ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroConsultaCat1Layout.createSequentialGroup()
                .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppFiltroConsultaCat1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ppFiltroConsultaCat1Layout.createSequentialGroup()
                                .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rotulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rotulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rotulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(csCategoriaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clsSituacaoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ppFiltroConsultaCat1Layout.createSequentialGroup()
                                .addComponent(rotulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ciIdCategoriaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ppFiltroConsultaCat1Layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(btCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(856, Short.MAX_VALUE))
        );
        ppFiltroConsultaCat1Layout.setVerticalGroup(
            ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroConsultaCat1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciIdCategoriaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCategoriaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsSituacaoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 595, Short.MAX_VALUE)
                .addGroup(ppFiltroConsultaCat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ppCadastroCat.add(ppFiltroConsultaCat1, java.awt.BorderLayout.CENTER);

        paCategoria.addTab("Cadastro / Alteração", ppCadastroCat);

        getContentPane().add(paCategoria, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        buscarCategoria();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        salvarAlterar = "Salvar";
        paCategoria.setSelectedComponent(ppCadastroCat);
        ppCadastroCat.setVisible(true);
        paCategoria.setEnabledAt(0, false);
        ciIdCategoriaCad.setInteger(0);
        ciIdCategoriaCad.setEditable(false);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void tpConsultaCatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpConsultaCatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpConsultaCatKeyPressed

    private void btCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCadastroActionPerformed
        limparCadastrar();
    }//GEN-LAST:event_btCancelarCadastroActionPerformed

    private void btSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCadastroActionPerformed
        salvarCategoria();
        if (resultado == true) {
            buscarCategoria();
        }
    }//GEN-LAST:event_btSalvarCadastroActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        salvarAlterar = "Alterar";
        alterarCategoria();
        if (resultado == true) {
            paCategoria.setSelectedComponent(ppCadastroCat);
            ppCadastroCat.setVisible(true);
            csCategoriaCad.requestFocus();
        } else {

        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirCategoria();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void rotulo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotulo2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rotulo2MouseClicked

    private void cscCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cscCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cscCategoriaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.matriz.componentesbasicos.Botao btAlterar;
    private br.com.martinello.matriz.componentesbasicos.Botao btCadastrar;
    private br.com.martinello.matriz.componentesbasicos.Botao btCancelarCadastro;
    private br.com.martinello.matriz.componentesbasicos.Botao btExcluir;
    private br.com.martinello.matriz.componentesbasicos.Botao btPesquisar;
    private br.com.martinello.matriz.componentesbasicos.Botao btSalvarCadastro;
    private br.com.martinello.matriz.componentesbasicos.CampoInteiro ciIdCategoria;
    private br.com.martinello.matriz.componentesbasicos.CampoInteiro ciIdCategoriaCad;
    private br.com.martinello.matriz.componentesbasicos.CampoListaSimples clsSituacaoCad;
    private br.com.martinello.matriz.componentesbasicos.CampoString csCategoriaCad;
    private br.com.martinello.matriz.componentesbasicos.consulta.CampoStringConsulta cscCategoria;
    private javax.swing.JScrollPane jScrollPane2;
    private br.com.martinello.matriz.componentesbasicos.paineis.JPStatus jpsCategoria;
    private javax.swing.JRadioButton jrbAtivoCatFiltro;
    private javax.swing.JRadioButton jrbInativoCatFiltro;
    private javax.swing.JScrollPane jspTabConsultaCat;
    private javax.swing.JTextArea jtaObservacao;
    private br.com.martinello.matriz.componentesbasicos.paineis.PainelAba paCategoria;
    private br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao ppCadastroCat;
    private br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao ppConsultaCat;
    private br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao ppFiltroConsultaCat;
    private br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao ppFiltroConsultaCat1;
    private br.com.martinello.matriz.componentesbasicos.paineis.PainelPadrao ppTabConsultaCat;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rotulo1;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rotulo2;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rotulo3;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rotulo4;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rotulo5;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rotulo6;
    private br.com.martinello.matriz.componentesbasicos.Rotulo rotulo7;
    private br.com.martinello.matriz.componentesbasicos.TabelaPadrao tpConsultaCat;
    // End of variables declaration//GEN-END:variables

    private void buscarCategoria() {
        try {
            filtroCategoria = new Categoria();
            lCategoria = new ArrayList<>();
            categoriaControl = new CategoriaControl();
            if (ciIdCategoria.getInteger() > 0) {
                filtroCategoria.setIdCategoria(ciIdCategoria.getInteger());
            }
            if (cscCategoria.getFiltroOld() != null) {
                filtroCategoria.setCategoria(cscCategoria.getFiltroOld().toString().toUpperCase());
            }

            String sitCat = "";
            if (jrbAtivoCatFiltro.isSelected()) {
                sitCat = "'" + "A" + "'";
            }
            if (jrbInativoCatFiltro.isSelected()) {
                if (sitCat.isEmpty()) {
                    sitCat = "'" + "I" + "'";
                } else {
                    sitCat = sitCat + ",'I'";
                }
            }
            System.out.println("sit:" + sitCat);
            filtroCategoria.setSituacao(sitCat);
            lCategoria = categoriaControl.listarCategoria(filtroCategoria);
            otmCategoria.setData(lCategoria);
            otmCategoria.fireTableDataChanged();

            tpConsultaCat.setForeground(Color.BLACK);

            jpsCategoria.setStatus("Pesquisa realizada com sucesso.", JPStatus.NORMAL);

            if (tpConsultaCat.getRowCount() > 0) {
                tpConsultaCat.packAll();
                tpConsultaCat.addRowSelectionInterval(tpConsultaCat.convertRowIndexToView(0), tpConsultaCat.convertRowIndexToView(0));
                tpConsultaCat.grabFocus();
            }
        } catch (ErroSistemaException ex) {
            jpsCategoria.setStatus(ex.getMessage(), JPStatus.ERRO);
        }
    }

    private boolean cadastrarCategoria() {
        try {
            categoria = new Categoria();
            if (cscCategoria.getString().isEmpty()) {
                JOptionPane.showMessageDialog(null, "É necessário preencher o campo descrição da categoria.");
            } else {
                categoria.setCategoria(cscCategoria.getString().toUpperCase());
            }
            int option = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente cadastrar nova categoria?", "Confirma", JOptionPane.YES_NO_OPTION);
            if (option == 1) {
                return resultado = false;
            }

            categoriaControl = new CategoriaControl();
            resultado = categoriaControl.insertCategoria(categoria);
        } catch (ErroSistemaException ex) {
            jpsCategoria.setStatus(ex.getMessage(), JPStatus.ERRO);
        }
        if (resultado = true) {
            ciIdCategoria.setValorPadrao(0);
            cscCategoria.setaValorFiltro(null);
        }
        return resultado;
    }

    private void limparCadastrar() {
        ciIdCategoriaCad.setValorPadrao(0);
        ciIdCategoriaCad.setEditable(false);
        csCategoriaCad.setText(null);
        jtaObservacao.setText(null);
        clsSituacaoCad.setSelectedIndex(2);
        salvarAlterar = "Salvar";
        paCategoria.setSelectedComponent(ppConsultaCat);
        paCategoria.setEnabledAt(1, false);
        ppCadastroCat.setVisible(false);
    }

    private boolean alterarCategoria() {
        categoria = new Categoria();
        resultado = false;
        int linha = tpConsultaCat.getSelectedRow();
        String codigo = "0";
        if (linha < 0) {
            jpsCategoria.setStatus("Selecione uma Categoria na Tabela, antes de clicar em alterar", JPStatus.ALERTA);
            return resultado;
        } else {
            codigo = (tpConsultaCat.getValueAt(linha, 0).toString());
            paCategoria.setSelectedComponent(ppCadastroCat);
            try {
                categoria = categoriaControl.buscarCategoria(codigo);
            } catch (ErroSistemaException ex) {
                ex.printStackTrace();
                jpsCategoria.setStatus("Erro ao Carregar a Filial", JPStatus.ERRO, ex);
                return resultado;
            }
            ciIdCategoriaCad.setInteger(categoria.getIdCategoria());
            ciIdCategoriaCad.setEditable(false);
            csCategoriaCad.setText(categoria.getCategoria());
            jtaObservacao.setText(categoria.getObsCategoria());
            if (categoria.getSituacao().equalsIgnoreCase("A")) {
                clsSituacaoCad.setSelectedIndex(0);
            } else {
                clsSituacaoCad.setSelectedIndex(1);
            }
            salvarAlterar = "Alterar";

            resultado = true;
        }
        return resultado;
    }

    private boolean salvarCategoria() {
        resultado = false;
        String status = clsSituacaoCad.getSelectedItem().toString();
        System.out.println("Teste:" + status);
        if (clsSituacaoCad.getSelectedItem().toString().equalsIgnoreCase(" ")) {
            jpsCategoria.setStatus("Erro é necessário informar o Status da Categoria!", JPStatus.ALERTA);
            return resultado;
        }
        if (csCategoriaCad.getString().equalsIgnoreCase("")) {
            jpsCategoria.setStatus("Erro é necessário informar a descrição da Categoria!", JPStatus.ALERTA);
            return resultado;
        }
        try {
            categoria = new Categoria();
            categoriaControl = new CategoriaControl();
            categoria.setIdCategoria(ciIdCategoriaCad.getInteger());
            categoria.setIdUsuario(usuario.getIdUsuario());
            categoria.setCategoria(csCategoriaCad.getString());
            categoria.setObsCategoria(jtaObservacao.getText());
            if (clsSituacaoCad.getSelectedItem().toString().equalsIgnoreCase("ATIVO")) {
                categoria.setSituacao("A");
            } else {
                categoria.setSituacao("I");
            }
            if (salvarAlterar.equalsIgnoreCase("Alterar")) {

                resultado = categoriaControl.updateCategoria(categoria);
            } else {
                resultado = categoriaControl.insertCategoria(categoria);
            }
        } catch (ErroSistemaException ex) {
            jpsCategoria.setStatus(ex.getMessage(), JPStatus.ERRO, ex);
            return resultado;
        }
        if (resultado = true) {
            jpsCategoria.setStatus("Registro Cadastrado com Sucesso!", JPStatus.NORMAL, 20);
            limparCadastrar();
        }
        return resultado;
    }

    private void excluirCategoria() {
        try {
            resultado = false;
            categoriaControl = new CategoriaControl();
            categoria = new Categoria();
            int linha = tpConsultaCat.getSelectedRow();
            if (linha < 0) {
                jpsCategoria.setStatus("Selecione uma Categoria na Tabela, antes de clicar em Excluir", JPStatus.ALERTA);
            } else {
                categoria.setIdCategoria(otmCategoria.getValue(tpConsultaCat.getLinhaSelecionada()).getIdCategoria());
                resultado = categoriaControl.excluir(categoria);
            }
        } catch (ErroSistemaException ex) {
            jpsCategoria.setStatus(ex.getMessage(), JPStatus.ERRO, ex);
        }
    }
}
